version: "3.9"
services:

  postgresql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    command: postgres -c max_connections=450 -c shared_buffers=32MB -c effective_cache_size=96MB -c work_mem=3MB -c maintenance_work_mem=12MB -c synchronous_commit=off -c fsync=off
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=rinha2025
      - POSTGRES_PASSWORD=rinha_2025
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "110MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
