DO $$
DECLARE
  table_record varchar;
BEGIN
  SELECT * INTO STRICT table_record FROM INFORMATION_SCHEMA.Tables WHERE table_schema = 'rinha2025' LIMIT 1;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      CREATE SCHEMA IF NOT EXISTS rinha2025 AUTHORIZATION rinha2025;

      ALTER DEFAULT PRIVILEGES FOR ROLE rinha2025 IN SCHEMA rinha2025
      GRANT ALL ON TABLES TO rinha2025;

END $$;
